project:
  type: book

book:
  title: "Building Science Atlas"
  author: "Patrick and Team"
  date: "today"
  repo-url: https://github.com/BuildingScienceRepository/Quarto-Book
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  reader-mode: true
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - energy_demand.qmd
    - simulation.qmd
    - neural_nets.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  epub:
    cover-image: cover.png
  pdf:
    documentclass: scrreprt
